# Generated by Django 3.2.10 on 2022-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PI', 'Piece'), ('KG', 'Kg'), ('LT', 'Lt'), ('MT', 'Metter')], max_length=2),
        ),
    ]
