# Generated by Django 3.2.10 on 2022-02-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_shoppingcart_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='sale.sale'),
        ),
    ]
